# Generated by Django 4.0 on 2022-01-08 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes_animetitans',
            name='episode_number',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animes_animetitans',
            name='episodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animetitans.episode_animetitans'),
        ),
    ]
