# Generated by Django 4.0 on 2022-01-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0002_animes_animetitans_episode_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animes_animetitans',
            name='episodes',
        ),
        migrations.AddField(
            model_name='animes_animetitans',
            name='episodes',
            field=models.ManyToManyField(to='animetitans.Episode_animetitans'),
        ),
    ]
