# Generated by Django 4.0 on 2022-01-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0003_remove_animes_animetitans_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animes_animetitans',
            name='episodes',
        ),
        migrations.AddField(
            model_name='episode_animetitans',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animes_animetitans',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='episode_animetitans',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animetitans.animes_animetitans'),
        ),
        migrations.AlterField(
            model_name='episode_animetitans',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
