# Generated by Django 4.0 on 2022-01-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0004_remove_animes_animetitans_episodes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animes_animetitans',
            old_name='episode_number',
            new_name='episodes',
        ),
    ]
