# Generated by Django 4.0 on 2022-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0006_animes_animetitans_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode_animetitans',
            name='title',
        ),
        migrations.AlterField(
            model_name='episode_animetitans',
            name='anime',
            field=models.CharField(max_length=1000),
        ),
    ]
