# Generated by Django 4.0 on 2022-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0007_remove_episode_animetitans_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode_animetitans',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
