# Generated by Django 4.0 on 2022-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0010_alter_episode_animetitans_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes_animetitans',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='animetitans.Categories_animetitans'),
        ),
    ]
