# Generated by Django 4.0 on 2022-01-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0013_suggestion_animetitans_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes_animetitans',
            name='categories',
            field=models.ManyToManyField(to='animetitans.Categories_animetitans'),
        ),
        migrations.AlterField(
            model_name='suggestion_animetitans',
            name='anime',
            field=models.ManyToManyField(to='animetitans.Animes_animetitans'),
        ),
    ]
