# Generated by Django 4.0 on 2022-01-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0015_rename_suggestion_animetitans_recommended_animetitans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommended_animetitans',
            new_name='Customized_Lists',
        ),
    ]
