# Generated by Django 4.0 on 2022-02-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replys',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='from_comment',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='like',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Replys',
        ),
    ]
