# Generated by Django 4.0 on 2022-02-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_alter_profile_use_profile_picture'),
        ('comments', '0002_remove_replys_dislike_remove_replys_from_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('dislike', models.ManyToManyField(related_name='+', to='accounts.Profile')),
                ('like', models.ManyToManyField(related_name='+', to='accounts.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('dislike', models.ManyToManyField(related_name='+', to='accounts.Profile')),
                ('from_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comments.comments')),
                ('like', models.ManyToManyField(related_name='+', to='accounts.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
