# Generated by Django 4.0 on 2022-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replys',
            name='from_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='replys',
            field=models.ManyToManyField(to='comments.Replys'),
        ),
    ]
