# Generated by Django 4.0 on 2022-02-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_profile_use_profile_picture'),
        ('comments', '0004_remove_replys_from_comment_comments_replys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='replys',
            field=models.ManyToManyField(blank=True, null=True, to='comments.Replys'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='replys',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='replys',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='replys',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='replys',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
