# Generated by Django 4.0 on 2022-02-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0017_alter_animes_animetitans_type_and_more'),
        ('comments', '0007_remove_comments_replys_comments_anime_comments_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='anime',
        ),
        migrations.AddField(
            model_name='comments',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animetitans.episode_animetitans'),
        ),
    ]
