# Generated by Django 4.0 on 2022-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitans', '0014_alter_animes_animetitans_categories_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchNow',
            field=models.ManyToManyField(to='animetitans.Animes_animetitans'),
        ),
    ]
