# Generated by Django 4.0 on 2022-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_added_date_profile_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
