# Generated by Django 4.0 on 2022-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
