# Generated by Django 4.0 on 2022-02-03 04:51

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=accounts.models.CloudinaryField(max_length=255),
        ),
    ]
