# Generated by Django 4.0 on 2022-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_profile_picture',
            field=models.BooleanField(default=True),
        ),
    ]
